# Generated by Django 3.1.3 on 2020-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fiction'), (2, 'Non-Fiction')], default=1),
            preserve_default=False,
        ),
    ]
